Waypoints
huskyroboticsteam/Simulator pull request #14
Opened 2023-12-08 03:00 UTC by imisaacwu

Moved metersToGPS to Utilities and generalized initial GPS location parameter
Added waypoints to the Simulator
Added 3 new console commands:
"help"-displays console commands and usage
"waypoints"-lists waypoints and their GPS coords
"waypoint \<name\>"-copies specified waypoint's GPS coords to clipboards (if it exists)

2024-01-09 06:01 UTC, abhaybd requested changes
Overall pretty good work! Left some comments below, and also can you make sure this is up to date with master?

2024-01-09 06:01 UTC, abhaybd commented on Assets/Scripts/CommandRegisterer.cs
> +                                            + GPS[1].ToString("0." + new string('#', 339));
339 is an awful lot of digits, and we won't ever need anywhere near that much. How about like 8 decimal places, which should be more than good enough? I understand it will truncate if there aren't any significant digits, but still even then it would be like 18ish digits or something, which is too much.

2024-01-09 06:01 UTC, abhaybd commented on Assets/Scripts/CommandRegisterer.cs
> +                    GPS[1].ToString("0." + new string('#', 339)) + ")");
Same as before, no need for these many digits. Also, could we explicitly label which one is lat and which one is lon?

2024-03-02 20:09 UTC, AyushKulk approved these changes
Looks good to me!

2024-05-14 01:11 UTC, huttongrabiel approved these changes

2024-05-14 01:11 UTC, merged